<?php
// Register our stylesheet
add_action( 'wp_enqueue_scripts', 'child_theme_enqueue_styles' );


// this original function was autogenerated with child theme creator plugin, it didn't work
function my_theme_enqueue_styles() {
    wp_enqueue_style( 'child-style', get_stylesheet_uri(),
        array( 'baskerville_style' ), 
        wp_get_theme()->get('Version') // this only works if you have Version in the style header
    );
    

} 
// use this instead
function child_theme_enqueue_styles() 
{
   
		//This is your parent stylesheet you can choose to include or exclude this by going to your Child Theme Settings under the "Settings" in your WP Dashboard
		wp_enqueue_style("parent-css", get_template_directory_uri()."/style.css" );
 
	//This is your child theme stylesheet = style.css
	wp_enqueue_style("child-css", get_stylesheet_uri());

}
 



